### ISSUE TITLE
Upgrade OpenStack to Zed

### ISSUE THREAD

**Issue by ra-beer** [osism/cloud-in-a-box#31]
Since OpenStack is now on Zed we should support it with the CiaB too.

**Comment by ra-beer** [comment]
Cloud in a box deployment with zed was successful. Please confirm if we should implement this by default @garloff @fkr @berendt 
This is the PR to do "zed" 😁: https://github.com/osism/cloud-in-a-box/pull/32

**Comment by garloff** [comment]
@ra-beer - I think the OpenStack version on C-i-a-B system should be aligned with what we do for testbed and production systems.
If we want to move forward a bit (weeks) faster and we have the test coverage to ensure that it works reasonably well, that would be welcome from my side.
We should IMVHO not become too aggressive about it - the CiaB system is not just used by OpenStack Devs but possibly folks that want to do Dev work on other layers (Containers, IAM, ...) who need the Infra and IaaS pieces to "just work" (TM).

**Comment by fkr** [comment]
@garloff since CiaB uses the testbed for deploying, it should do the default for testbed and roll out whatever the default for testbed is imho. Since CiaB and testbed (by name already in the later) are _test_ environments, I think they should serve the purpose and allow us to go faster (which is why i 👍 the #32 PR).

**Comment by fkr** [comment]
Discussed in IaaS Call in CW3: CiaB should reflect stable **not** latest.
